/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "EZI2C.h"
#include "EZI2C_PINS.h"
#include "EZI2C_PVT.h"
#include "EZI2C_EZI2C.h"
#include "EZI2C_EZI2C_PVT.h"
#include "EZI2C_BOOT.h"
#include "CapSense.h"
#include "CapSense_Control.h"
#include "CapSense_Filter.h"
#include "CapSense_Processing.h"
#include "CapSense_Sensing.h"
#include "CapSense_Structure.h"
#include "CapSense_Tuner.h"
#include "CapSense_Configuration.h"
#include "CapSense_SensingCSD_LL.h"
#include "CapSense_SensingCSX_LL.h"
#include "CapSense_RegisterMap.h"
#include "CapSense_Centroid_LL.h"
#include "SmartIO_Port2.h"
#include "TCPWM1.h"
#include "Clock_1.h"
#include "LED1.h"
#include "LED1_aliases.h"
#include "TCPWM2.h"
#include "LED11.h"
#include "LED11_aliases.h"
#include "LED10.h"
#include "LED10_aliases.h"
#include "LED9.h"
#include "LED9_aliases.h"
#include "LED8.h"
#include "LED8_aliases.h"
#include "LED7.h"
#include "LED7_aliases.h"
#include "LED6.h"
#include "LED6_aliases.h"
#include "LED5.h"
#include "LED5_aliases.h"
#include "LED4.h"
#include "LED4_aliases.h"
#include "EZI2C_SCBCLK.h"
#include "EZI2C_sda.h"
#include "EZI2C_sda_aliases.h"
#include "EZI2C_scl.h"
#include "EZI2C_scl_aliases.h"
#include "EZI2C_SCB_IRQ.h"
#include "CapSense_ISR.h"
#include "cy_em_eeprom.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cm0plus_psoc4.h"
#include "CyLFClk.h"

/*[]*/

