/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LED1.h"
#include "LED1_aliases.h"
#include "UART.h"
#include "UART_SPI_UART.h"
#include "UART_PINS.h"
#include "UART_SPI_UART_PVT.h"
#include "UART_PVT.h"
#include "UART_BOOT.h"
#include "I2CS.h"
#include "I2CS_I2C.h"
#include "I2CS_PINS.h"
#include "I2CS_I2C_PVT.h"
#include "I2CS_PVT.h"
#include "I2CS_BOOT.h"
#include "CapSense_1.h"
#include "CapSense_1_Control.h"
#include "CapSense_1_Filter.h"
#include "CapSense_1_Processing.h"
#include "CapSense_1_Sensing.h"
#include "CapSense_1_Structure.h"
#include "CapSense_1_Tuner.h"
#include "CapSense_1_Configuration.h"
#include "CapSense_1_SensingCSD_LL.h"
#include "CapSense_1_RegisterMap.h"
#include "UART_SCBCLK.h"
#include "UART_tx.h"
#include "UART_tx_aliases.h"
#include "I2CS_SCBCLK.h"
#include "I2CS_sda.h"
#include "I2CS_sda_aliases.h"
#include "I2CS_scl.h"
#include "I2CS_scl_aliases.h"
#include "I2CS_SCB_IRQ.h"
#include "CapSense_1_ISR.h"
#include "cy_em_eeprom.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cm0plus_psoc4.h"
#include "CyLFClk.h"

/*[]*/

